name: dist
on: [ push,pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:  [27.1]

    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v2
      - name: install yarn
        run: |
          sudo apt update 
          sudo apt install npm
          npm install -g yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: dist tailwind
        run: |
          yarn dist:tailwind
      - name: build org
        run: |
            yarn dist:org
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            deploy_key: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist